// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/BuildResultsPB.proto

package molecular_dynamics.oligosaccharide_builder;

public final class BuildResultsPB {
  private BuildResultsPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BuildResultsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .molecular_dynamics.oligosaccharide_builder.BuildResults.Structure structure = 1;
    java.util.List<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure> 
        getStructureList();
    molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure getStructure(int index);
    int getStructureCount();
    java.util.List<? extends molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.StructureOrBuilder> 
        getStructureOrBuilderList();
    molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.StructureOrBuilder getStructureOrBuilder(
        int index);
  }
  public static final class BuildResults extends
      com.google.protobuf.GeneratedMessage
      implements BuildResultsOrBuilder {
    // Use BuildResults.newBuilder() to construct.
    private BuildResults(Builder builder) {
      super(builder);
    }
    private BuildResults(boolean noInit) {}
    
    private static final BuildResults defaultInstance;
    public static BuildResults getDefaultInstance() {
      return defaultInstance;
    }
    
    public BuildResults getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_fieldAccessorTable;
    }
    
    public interface FlexibleLinkageOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required int32 index = 1;
      boolean hasIndex();
      int getIndex();
      
      // required .molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage.Angle angle = 2;
      boolean hasAngle();
      molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Angle getAngle();
      
      // required double value = 3;
      boolean hasValue();
      double getValue();
    }
    public static final class FlexibleLinkage extends
        com.google.protobuf.GeneratedMessage
        implements FlexibleLinkageOrBuilder {
      // Use FlexibleLinkage.newBuilder() to construct.
      private FlexibleLinkage(Builder builder) {
        super(builder);
      }
      private FlexibleLinkage(boolean noInit) {}
      
      private static final FlexibleLinkage defaultInstance;
      public static FlexibleLinkage getDefaultInstance() {
        return defaultInstance;
      }
      
      public FlexibleLinkage getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_FlexibleLinkage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_FlexibleLinkage_fieldAccessorTable;
      }
      
      public enum Angle
          implements com.google.protobuf.ProtocolMessageEnum {
        PHI(0, 0),
        PSI(1, 1),
        OMEGA(2, 2),
        ;
        
        public static final int PHI_VALUE = 0;
        public static final int PSI_VALUE = 1;
        public static final int OMEGA_VALUE = 2;
        
        
        public final int getNumber() { return value; }
        
        public static Angle valueOf(int value) {
          switch (value) {
            case 0: return PHI;
            case 1: return PSI;
            case 2: return OMEGA;
            default: return null;
          }
        }
        
        public static com.google.protobuf.Internal.EnumLiteMap<Angle>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<Angle>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<Angle>() {
                public Angle findValueByNumber(int number) {
                  return Angle.valueOf(number);
                }
              };
        
        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.getDescriptor().getEnumTypes().get(0);
        }
        
        private static final Angle[] VALUES = {
          PHI, PSI, OMEGA, 
        };
        
        public static Angle valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }
        
        private final int index;
        private final int value;
        
        private Angle(int index, int value) {
          this.index = index;
          this.value = value;
        }
        
        // @@protoc_insertion_point(enum_scope:molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage.Angle)
      }
      
      private int bitField0_;
      // required int32 index = 1;
      public static final int INDEX_FIELD_NUMBER = 1;
      private int index_;
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getIndex() {
        return index_;
      }
      
      // required .molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage.Angle angle = 2;
      public static final int ANGLE_FIELD_NUMBER = 2;
      private molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Angle angle_;
      public boolean hasAngle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Angle getAngle() {
        return angle_;
      }
      
      // required double value = 3;
      public static final int VALUE_FIELD_NUMBER = 3;
      private double value_;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getValue() {
        return value_;
      }
      
      private void initFields() {
        index_ = 0;
        angle_ = molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Angle.PHI;
        value_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasIndex()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasAngle()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, index_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, angle_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeDouble(3, value_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, index_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, angle_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, value_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_FlexibleLinkage_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_FlexibleLinkage_fieldAccessorTable;
        }
        
        // Construct using molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          index_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          angle_ = molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Angle.PHI;
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.getDescriptor();
        }
        
        public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage getDefaultInstanceForType() {
          return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.getDefaultInstance();
        }
        
        public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage build() {
          molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage buildPartial() {
          molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage result = new molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.index_ = index_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.angle_ = angle_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage) {
            return mergeFrom((molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage other) {
          if (other == molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.getDefaultInstance()) return this;
          if (other.hasIndex()) {
            setIndex(other.getIndex());
          }
          if (other.hasAngle()) {
            setAngle(other.getAngle());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasIndex()) {
            
            return false;
          }
          if (!hasAngle()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                index_ = input.readInt32();
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Angle value = molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Angle.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  angle_ = value;
                }
                break;
              }
              case 25: {
                bitField0_ |= 0x00000004;
                value_ = input.readDouble();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required int32 index = 1;
        private int index_ ;
        public boolean hasIndex() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getIndex() {
          return index_;
        }
        public Builder setIndex(int value) {
          bitField0_ |= 0x00000001;
          index_ = value;
          onChanged();
          return this;
        }
        public Builder clearIndex() {
          bitField0_ = (bitField0_ & ~0x00000001);
          index_ = 0;
          onChanged();
          return this;
        }
        
        // required .molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage.Angle angle = 2;
        private molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Angle angle_ = molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Angle.PHI;
        public boolean hasAngle() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Angle getAngle() {
          return angle_;
        }
        public Builder setAngle(molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Angle value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          angle_ = value;
          onChanged();
          return this;
        }
        public Builder clearAngle() {
          bitField0_ = (bitField0_ & ~0x00000002);
          angle_ = molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Angle.PHI;
          onChanged();
          return this;
        }
        
        // required double value = 3;
        private double value_ ;
        public boolean hasValue() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public double getValue() {
          return value_;
        }
        public Builder setValue(double value) {
          bitField0_ |= 0x00000004;
          value_ = value;
          onChanged();
          return this;
        }
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000004);
          value_ = 0D;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage)
      }
      
      static {
        defaultInstance = new FlexibleLinkage(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage)
    }
    
    public interface StructureOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // repeated .molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage flexible_linkage = 1;
      java.util.List<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage> 
          getFlexibleLinkageList();
      molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage getFlexibleLinkage(int index);
      int getFlexibleLinkageCount();
      java.util.List<? extends molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkageOrBuilder> 
          getFlexibleLinkageOrBuilderList();
      molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkageOrBuilder getFlexibleLinkageOrBuilder(
          int index);
    }
    public static final class Structure extends
        com.google.protobuf.GeneratedMessage
        implements StructureOrBuilder {
      // Use Structure.newBuilder() to construct.
      private Structure(Builder builder) {
        super(builder);
      }
      private Structure(boolean noInit) {}
      
      private static final Structure defaultInstance;
      public static Structure getDefaultInstance() {
        return defaultInstance;
      }
      
      public Structure getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_Structure_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_Structure_fieldAccessorTable;
      }
      
      // repeated .molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage flexible_linkage = 1;
      public static final int FLEXIBLE_LINKAGE_FIELD_NUMBER = 1;
      private java.util.List<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage> flexibleLinkage_;
      public java.util.List<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage> getFlexibleLinkageList() {
        return flexibleLinkage_;
      }
      public java.util.List<? extends molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkageOrBuilder> 
          getFlexibleLinkageOrBuilderList() {
        return flexibleLinkage_;
      }
      public int getFlexibleLinkageCount() {
        return flexibleLinkage_.size();
      }
      public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage getFlexibleLinkage(int index) {
        return flexibleLinkage_.get(index);
      }
      public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkageOrBuilder getFlexibleLinkageOrBuilder(
          int index) {
        return flexibleLinkage_.get(index);
      }
      
      private void initFields() {
        flexibleLinkage_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        for (int i = 0; i < getFlexibleLinkageCount(); i++) {
          if (!getFlexibleLinkage(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < flexibleLinkage_.size(); i++) {
          output.writeMessage(1, flexibleLinkage_.get(i));
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        for (int i = 0; i < flexibleLinkage_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, flexibleLinkage_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.StructureOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_Structure_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_Structure_fieldAccessorTable;
        }
        
        // Construct using molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getFlexibleLinkageFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          if (flexibleLinkageBuilder_ == null) {
            flexibleLinkage_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            flexibleLinkageBuilder_.clear();
          }
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.getDescriptor();
        }
        
        public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure getDefaultInstanceForType() {
          return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.getDefaultInstance();
        }
        
        public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure build() {
          molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure buildPartial() {
          molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure result = new molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure(this);
          int from_bitField0_ = bitField0_;
          if (flexibleLinkageBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              flexibleLinkage_ = java.util.Collections.unmodifiableList(flexibleLinkage_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.flexibleLinkage_ = flexibleLinkage_;
          } else {
            result.flexibleLinkage_ = flexibleLinkageBuilder_.build();
          }
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure) {
            return mergeFrom((molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure other) {
          if (other == molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.getDefaultInstance()) return this;
          if (flexibleLinkageBuilder_ == null) {
            if (!other.flexibleLinkage_.isEmpty()) {
              if (flexibleLinkage_.isEmpty()) {
                flexibleLinkage_ = other.flexibleLinkage_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureFlexibleLinkageIsMutable();
                flexibleLinkage_.addAll(other.flexibleLinkage_);
              }
              onChanged();
            }
          } else {
            if (!other.flexibleLinkage_.isEmpty()) {
              if (flexibleLinkageBuilder_.isEmpty()) {
                flexibleLinkageBuilder_.dispose();
                flexibleLinkageBuilder_ = null;
                flexibleLinkage_ = other.flexibleLinkage_;
                bitField0_ = (bitField0_ & ~0x00000001);
                flexibleLinkageBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getFlexibleLinkageFieldBuilder() : null;
              } else {
                flexibleLinkageBuilder_.addAllMessages(other.flexibleLinkage_);
              }
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          for (int i = 0; i < getFlexibleLinkageCount(); i++) {
            if (!getFlexibleLinkage(i).isInitialized()) {
              
              return false;
            }
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Builder subBuilder = molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.newBuilder();
                input.readMessage(subBuilder, extensionRegistry);
                addFlexibleLinkage(subBuilder.buildPartial());
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // repeated .molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage flexible_linkage = 1;
        private java.util.List<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage> flexibleLinkage_ =
          java.util.Collections.emptyList();
        private void ensureFlexibleLinkageIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            flexibleLinkage_ = new java.util.ArrayList<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage>(flexibleLinkage_);
            bitField0_ |= 0x00000001;
           }
        }
        
        private com.google.protobuf.RepeatedFieldBuilder<
            molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Builder, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkageOrBuilder> flexibleLinkageBuilder_;
        
        public java.util.List<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage> getFlexibleLinkageList() {
          if (flexibleLinkageBuilder_ == null) {
            return java.util.Collections.unmodifiableList(flexibleLinkage_);
          } else {
            return flexibleLinkageBuilder_.getMessageList();
          }
        }
        public int getFlexibleLinkageCount() {
          if (flexibleLinkageBuilder_ == null) {
            return flexibleLinkage_.size();
          } else {
            return flexibleLinkageBuilder_.getCount();
          }
        }
        public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage getFlexibleLinkage(int index) {
          if (flexibleLinkageBuilder_ == null) {
            return flexibleLinkage_.get(index);
          } else {
            return flexibleLinkageBuilder_.getMessage(index);
          }
        }
        public Builder setFlexibleLinkage(
            int index, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage value) {
          if (flexibleLinkageBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureFlexibleLinkageIsMutable();
            flexibleLinkage_.set(index, value);
            onChanged();
          } else {
            flexibleLinkageBuilder_.setMessage(index, value);
          }
          return this;
        }
        public Builder setFlexibleLinkage(
            int index, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Builder builderForValue) {
          if (flexibleLinkageBuilder_ == null) {
            ensureFlexibleLinkageIsMutable();
            flexibleLinkage_.set(index, builderForValue.build());
            onChanged();
          } else {
            flexibleLinkageBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        public Builder addFlexibleLinkage(molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage value) {
          if (flexibleLinkageBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureFlexibleLinkageIsMutable();
            flexibleLinkage_.add(value);
            onChanged();
          } else {
            flexibleLinkageBuilder_.addMessage(value);
          }
          return this;
        }
        public Builder addFlexibleLinkage(
            int index, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage value) {
          if (flexibleLinkageBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureFlexibleLinkageIsMutable();
            flexibleLinkage_.add(index, value);
            onChanged();
          } else {
            flexibleLinkageBuilder_.addMessage(index, value);
          }
          return this;
        }
        public Builder addFlexibleLinkage(
            molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Builder builderForValue) {
          if (flexibleLinkageBuilder_ == null) {
            ensureFlexibleLinkageIsMutable();
            flexibleLinkage_.add(builderForValue.build());
            onChanged();
          } else {
            flexibleLinkageBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        public Builder addFlexibleLinkage(
            int index, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Builder builderForValue) {
          if (flexibleLinkageBuilder_ == null) {
            ensureFlexibleLinkageIsMutable();
            flexibleLinkage_.add(index, builderForValue.build());
            onChanged();
          } else {
            flexibleLinkageBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        public Builder addAllFlexibleLinkage(
            java.lang.Iterable<? extends molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage> values) {
          if (flexibleLinkageBuilder_ == null) {
            ensureFlexibleLinkageIsMutable();
            super.addAll(values, flexibleLinkage_);
            onChanged();
          } else {
            flexibleLinkageBuilder_.addAllMessages(values);
          }
          return this;
        }
        public Builder clearFlexibleLinkage() {
          if (flexibleLinkageBuilder_ == null) {
            flexibleLinkage_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            flexibleLinkageBuilder_.clear();
          }
          return this;
        }
        public Builder removeFlexibleLinkage(int index) {
          if (flexibleLinkageBuilder_ == null) {
            ensureFlexibleLinkageIsMutable();
            flexibleLinkage_.remove(index);
            onChanged();
          } else {
            flexibleLinkageBuilder_.remove(index);
          }
          return this;
        }
        public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Builder getFlexibleLinkageBuilder(
            int index) {
          return getFlexibleLinkageFieldBuilder().getBuilder(index);
        }
        public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkageOrBuilder getFlexibleLinkageOrBuilder(
            int index) {
          if (flexibleLinkageBuilder_ == null) {
            return flexibleLinkage_.get(index);  } else {
            return flexibleLinkageBuilder_.getMessageOrBuilder(index);
          }
        }
        public java.util.List<? extends molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkageOrBuilder> 
             getFlexibleLinkageOrBuilderList() {
          if (flexibleLinkageBuilder_ != null) {
            return flexibleLinkageBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(flexibleLinkage_);
          }
        }
        public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Builder addFlexibleLinkageBuilder() {
          return getFlexibleLinkageFieldBuilder().addBuilder(
              molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.getDefaultInstance());
        }
        public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Builder addFlexibleLinkageBuilder(
            int index) {
          return getFlexibleLinkageFieldBuilder().addBuilder(
              index, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.getDefaultInstance());
        }
        public java.util.List<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Builder> 
             getFlexibleLinkageBuilderList() {
          return getFlexibleLinkageFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Builder, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkageOrBuilder> 
            getFlexibleLinkageFieldBuilder() {
          if (flexibleLinkageBuilder_ == null) {
            flexibleLinkageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Builder, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkageOrBuilder>(
                    flexibleLinkage_,
                    ((bitField0_ & 0x00000001) == 0x00000001),
                    getParentForChildren(),
                    isClean());
            flexibleLinkage_ = null;
          }
          return flexibleLinkageBuilder_;
        }
        
        // @@protoc_insertion_point(builder_scope:molecular_dynamics.oligosaccharide_builder.BuildResults.Structure)
      }
      
      static {
        defaultInstance = new Structure(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:molecular_dynamics.oligosaccharide_builder.BuildResults.Structure)
    }
    
    // repeated .molecular_dynamics.oligosaccharide_builder.BuildResults.Structure structure = 1;
    public static final int STRUCTURE_FIELD_NUMBER = 1;
    private java.util.List<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure> structure_;
    public java.util.List<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure> getStructureList() {
      return structure_;
    }
    public java.util.List<? extends molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.StructureOrBuilder> 
        getStructureOrBuilderList() {
      return structure_;
    }
    public int getStructureCount() {
      return structure_.size();
    }
    public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure getStructure(int index) {
      return structure_.get(index);
    }
    public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.StructureOrBuilder getStructureOrBuilder(
        int index) {
      return structure_.get(index);
    }
    
    private void initFields() {
      structure_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getStructureCount(); i++) {
        if (!getStructure(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < structure_.size(); i++) {
        output.writeMessage(1, structure_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < structure_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, structure_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResultsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_fieldAccessorTable;
      }
      
      // Construct using molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStructureFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (structureBuilder_ == null) {
          structure_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          structureBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.getDescriptor();
      }
      
      public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults getDefaultInstanceForType() {
        return molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.getDefaultInstance();
      }
      
      public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults build() {
        molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults buildPartial() {
        molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults result = new molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults(this);
        int from_bitField0_ = bitField0_;
        if (structureBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            structure_ = java.util.Collections.unmodifiableList(structure_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.structure_ = structure_;
        } else {
          result.structure_ = structureBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults) {
          return mergeFrom((molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults other) {
        if (other == molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.getDefaultInstance()) return this;
        if (structureBuilder_ == null) {
          if (!other.structure_.isEmpty()) {
            if (structure_.isEmpty()) {
              structure_ = other.structure_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStructureIsMutable();
              structure_.addAll(other.structure_);
            }
            onChanged();
          }
        } else {
          if (!other.structure_.isEmpty()) {
            if (structureBuilder_.isEmpty()) {
              structureBuilder_.dispose();
              structureBuilder_ = null;
              structure_ = other.structure_;
              bitField0_ = (bitField0_ & ~0x00000001);
              structureBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStructureFieldBuilder() : null;
            } else {
              structureBuilder_.addAllMessages(other.structure_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getStructureCount(); i++) {
          if (!getStructure(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.Builder subBuilder = molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addStructure(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .molecular_dynamics.oligosaccharide_builder.BuildResults.Structure structure = 1;
      private java.util.List<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure> structure_ =
        java.util.Collections.emptyList();
      private void ensureStructureIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          structure_ = new java.util.ArrayList<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure>(structure_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.Builder, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.StructureOrBuilder> structureBuilder_;
      
      public java.util.List<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure> getStructureList() {
        if (structureBuilder_ == null) {
          return java.util.Collections.unmodifiableList(structure_);
        } else {
          return structureBuilder_.getMessageList();
        }
      }
      public int getStructureCount() {
        if (structureBuilder_ == null) {
          return structure_.size();
        } else {
          return structureBuilder_.getCount();
        }
      }
      public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure getStructure(int index) {
        if (structureBuilder_ == null) {
          return structure_.get(index);
        } else {
          return structureBuilder_.getMessage(index);
        }
      }
      public Builder setStructure(
          int index, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure value) {
        if (structureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStructureIsMutable();
          structure_.set(index, value);
          onChanged();
        } else {
          structureBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setStructure(
          int index, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.Builder builderForValue) {
        if (structureBuilder_ == null) {
          ensureStructureIsMutable();
          structure_.set(index, builderForValue.build());
          onChanged();
        } else {
          structureBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addStructure(molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure value) {
        if (structureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStructureIsMutable();
          structure_.add(value);
          onChanged();
        } else {
          structureBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addStructure(
          int index, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure value) {
        if (structureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStructureIsMutable();
          structure_.add(index, value);
          onChanged();
        } else {
          structureBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addStructure(
          molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.Builder builderForValue) {
        if (structureBuilder_ == null) {
          ensureStructureIsMutable();
          structure_.add(builderForValue.build());
          onChanged();
        } else {
          structureBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addStructure(
          int index, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.Builder builderForValue) {
        if (structureBuilder_ == null) {
          ensureStructureIsMutable();
          structure_.add(index, builderForValue.build());
          onChanged();
        } else {
          structureBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllStructure(
          java.lang.Iterable<? extends molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure> values) {
        if (structureBuilder_ == null) {
          ensureStructureIsMutable();
          super.addAll(values, structure_);
          onChanged();
        } else {
          structureBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearStructure() {
        if (structureBuilder_ == null) {
          structure_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          structureBuilder_.clear();
        }
        return this;
      }
      public Builder removeStructure(int index) {
        if (structureBuilder_ == null) {
          ensureStructureIsMutable();
          structure_.remove(index);
          onChanged();
        } else {
          structureBuilder_.remove(index);
        }
        return this;
      }
      public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.Builder getStructureBuilder(
          int index) {
        return getStructureFieldBuilder().getBuilder(index);
      }
      public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.StructureOrBuilder getStructureOrBuilder(
          int index) {
        if (structureBuilder_ == null) {
          return structure_.get(index);  } else {
          return structureBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.StructureOrBuilder> 
           getStructureOrBuilderList() {
        if (structureBuilder_ != null) {
          return structureBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(structure_);
        }
      }
      public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.Builder addStructureBuilder() {
        return getStructureFieldBuilder().addBuilder(
            molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.getDefaultInstance());
      }
      public molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.Builder addStructureBuilder(
          int index) {
        return getStructureFieldBuilder().addBuilder(
            index, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.getDefaultInstance());
      }
      public java.util.List<molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.Builder> 
           getStructureBuilderList() {
        return getStructureFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.Builder, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.StructureOrBuilder> 
          getStructureFieldBuilder() {
        if (structureBuilder_ == null) {
          structureBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.Builder, molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.StructureOrBuilder>(
                  structure_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          structure_ = null;
        }
        return structureBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:molecular_dynamics.oligosaccharide_builder.BuildResults)
    }
    
    static {
      defaultInstance = new BuildResults(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:molecular_dynamics.oligosaccharide_builder.BuildResults)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_FlexibleLinkage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_FlexibleLinkage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_Structure_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_Structure_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032proto/BuildResultsPB.proto\022*molecular_" +
      "dynamics.oligosaccharide_builder\"\215\003\n\014Bui" +
      "ldResults\022U\n\tstructure\030\001 \003(\0132B.molecular" +
      "_dynamics.oligosaccharide_builder.BuildR" +
      "esults.Structure\032\264\001\n\017FlexibleLinkage\022\r\n\005" +
      "index\030\001 \002(\005\022]\n\005angle\030\002 \002(\0162N.molecular_d" +
      "ynamics.oligosaccharide_builder.BuildRes" +
      "ults.FlexibleLinkage.Angle\022\r\n\005value\030\003 \002(" +
      "\001\"$\n\005Angle\022\007\n\003PHI\020\000\022\007\n\003PSI\020\001\022\t\n\005OMEGA\020\002\032" +
      "o\n\tStructure\022b\n\020flexible_linkage\030\001 \003(\0132H",
      ".molecular_dynamics.oligosaccharide_buil" +
      "der.BuildResults.FlexibleLinkage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_descriptor,
              new java.lang.String[] { "Structure", },
              molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.class,
              molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Builder.class);
          internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_FlexibleLinkage_descriptor =
            internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_descriptor.getNestedTypes().get(0);
          internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_FlexibleLinkage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_FlexibleLinkage_descriptor,
              new java.lang.String[] { "Index", "Angle", "Value", },
              molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.class,
              molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.FlexibleLinkage.Builder.class);
          internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_Structure_descriptor =
            internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_descriptor.getNestedTypes().get(1);
          internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_Structure_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_molecular_dynamics_oligosaccharide_builder_BuildResults_Structure_descriptor,
              new java.lang.String[] { "FlexibleLinkage", },
              molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.class,
              molecular_dynamics.oligosaccharide_builder.BuildResultsPB.BuildResults.Structure.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
