
<a href="/"><img src="/img/logo.jpg"  alt="GLYCAM logo" /></a>
<div id="nav">
<ul class="menu" id="menu">
 <li>
  <a href="#" class="menulink">About</a>
  <ul>
   <li>
    <a href="/about.jsp">Woods Group</a>
   </li>
  </ul>
 </li>
 <li>
  <a href="#" class="menulink">FAQ</a>
 </li>
 <li>
  <a href="/tools/" class="menulink">Tools</a>
  <ul>
   <li>
    <a href="/tools/molecular-dynamics" class="sub">Molecular Dynamics</a>
    <ul>
     <li class="topline">
      <a href="/tools/molecular-dynamics/oligosaccharide-builder/build-glycan">Build an Oligosaccharide</a>
     </li>
     <li>
      <a href="/tools/molecular-dynamics/glycoprotein-builder/upload-pdb">Build a Glycoprotein</a>
     </li>
    </ul>
   </li>
   <li>
    <a href="#">Docking and Virtual Screening</a>
   </li>
   <li>
    <a href="#">Crystallography</a>
   </li>
   <li>
    <a href="#">Visualization Only</a>
   </li>
   <li>
    <a href="#">Analysis</a>
   </li>
  </ul>
 </li>
 <li>
  <a href="#" class="menulink">Projects</a>
  <ul>
   <li>
    <a href="#" class="sub">GEMS</a>
    <ul>
     <li class="topline">
      <a href="/projects/gems/docs/">Documentation</a>
     </li>
    </ul>
   </li>
  </ul>
 </li>
 <li>
  <a href="#" class="menulink">Downloads</a>
 </li>
</ul>
</div>
<br /><br />
<div class="clear"></div>
<script type="text/javascript">
        var menu=new menu.dd("menu");
        menu.init("menu","menuhover");
</script>
