// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/BuildResultsPB.proto

#ifndef PROTOBUF_proto_2fBuildResultsPB_2eproto__INCLUDED
#define PROTOBUF_proto_2fBuildResultsPB_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace molecular_dynamics {
namespace oligosaccharide_builder {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2fBuildResultsPB_2eproto();
void protobuf_AssignDesc_proto_2fBuildResultsPB_2eproto();
void protobuf_ShutdownFile_proto_2fBuildResultsPB_2eproto();

class BuildResults;
class BuildResults_FlexibleLinkage;
class BuildResults_Structure;

enum BuildResults_FlexibleLinkage_Angle {
  BuildResults_FlexibleLinkage_Angle_PHI = 0,
  BuildResults_FlexibleLinkage_Angle_PSI = 1,
  BuildResults_FlexibleLinkage_Angle_OMEGA = 2
};
bool BuildResults_FlexibleLinkage_Angle_IsValid(int value);
const BuildResults_FlexibleLinkage_Angle BuildResults_FlexibleLinkage_Angle_Angle_MIN = BuildResults_FlexibleLinkage_Angle_PHI;
const BuildResults_FlexibleLinkage_Angle BuildResults_FlexibleLinkage_Angle_Angle_MAX = BuildResults_FlexibleLinkage_Angle_OMEGA;
const int BuildResults_FlexibleLinkage_Angle_Angle_ARRAYSIZE = BuildResults_FlexibleLinkage_Angle_Angle_MAX + 1;

const ::google::protobuf::EnumDescriptor* BuildResults_FlexibleLinkage_Angle_descriptor();
inline const ::std::string& BuildResults_FlexibleLinkage_Angle_Name(BuildResults_FlexibleLinkage_Angle value) {
  return ::google::protobuf::internal::NameOfEnum(
    BuildResults_FlexibleLinkage_Angle_descriptor(), value);
}
inline bool BuildResults_FlexibleLinkage_Angle_Parse(
    const ::std::string& name, BuildResults_FlexibleLinkage_Angle* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BuildResults_FlexibleLinkage_Angle>(
    BuildResults_FlexibleLinkage_Angle_descriptor(), name, value);
}
// ===================================================================

class BuildResults_FlexibleLinkage : public ::google::protobuf::Message {
 public:
  BuildResults_FlexibleLinkage();
  virtual ~BuildResults_FlexibleLinkage();
  
  BuildResults_FlexibleLinkage(const BuildResults_FlexibleLinkage& from);
  
  inline BuildResults_FlexibleLinkage& operator=(const BuildResults_FlexibleLinkage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const BuildResults_FlexibleLinkage& default_instance();
  
  void Swap(BuildResults_FlexibleLinkage* other);
  
  // implements Message ----------------------------------------------
  
  BuildResults_FlexibleLinkage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BuildResults_FlexibleLinkage& from);
  void MergeFrom(const BuildResults_FlexibleLinkage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef BuildResults_FlexibleLinkage_Angle Angle;
  static const Angle PHI = BuildResults_FlexibleLinkage_Angle_PHI;
  static const Angle PSI = BuildResults_FlexibleLinkage_Angle_PSI;
  static const Angle OMEGA = BuildResults_FlexibleLinkage_Angle_OMEGA;
  static inline bool Angle_IsValid(int value) {
    return BuildResults_FlexibleLinkage_Angle_IsValid(value);
  }
  static const Angle Angle_MIN =
    BuildResults_FlexibleLinkage_Angle_Angle_MIN;
  static const Angle Angle_MAX =
    BuildResults_FlexibleLinkage_Angle_Angle_MAX;
  static const int Angle_ARRAYSIZE =
    BuildResults_FlexibleLinkage_Angle_Angle_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Angle_descriptor() {
    return BuildResults_FlexibleLinkage_Angle_descriptor();
  }
  static inline const ::std::string& Angle_Name(Angle value) {
    return BuildResults_FlexibleLinkage_Angle_Name(value);
  }
  static inline bool Angle_Parse(const ::std::string& name,
      Angle* value) {
    return BuildResults_FlexibleLinkage_Angle_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required int32 index = 1;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 1;
  inline ::google::protobuf::int32 index() const;
  inline void set_index(::google::protobuf::int32 value);
  
  // required .molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage.Angle angle = 2;
  inline bool has_angle() const;
  inline void clear_angle();
  static const int kAngleFieldNumber = 2;
  inline ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage_Angle angle() const;
  inline void set_angle(::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage_Angle value);
  
  // required double value = 3;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 3;
  inline double value() const;
  inline void set_value(double value);
  
  // @@protoc_insertion_point(class_scope:molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage)
 private:
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_angle();
  inline void clear_has_angle();
  inline void set_has_value();
  inline void clear_has_value();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 index_;
  int angle_;
  double value_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_proto_2fBuildResultsPB_2eproto();
  friend void protobuf_AssignDesc_proto_2fBuildResultsPB_2eproto();
  friend void protobuf_ShutdownFile_proto_2fBuildResultsPB_2eproto();
  
  void InitAsDefaultInstance();
  static BuildResults_FlexibleLinkage* default_instance_;
};
// -------------------------------------------------------------------

class BuildResults_Structure : public ::google::protobuf::Message {
 public:
  BuildResults_Structure();
  virtual ~BuildResults_Structure();
  
  BuildResults_Structure(const BuildResults_Structure& from);
  
  inline BuildResults_Structure& operator=(const BuildResults_Structure& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const BuildResults_Structure& default_instance();
  
  void Swap(BuildResults_Structure* other);
  
  // implements Message ----------------------------------------------
  
  BuildResults_Structure* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BuildResults_Structure& from);
  void MergeFrom(const BuildResults_Structure& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage flexible_linkage = 1;
  inline int flexible_linkage_size() const;
  inline void clear_flexible_linkage();
  static const int kFlexibleLinkageFieldNumber = 1;
  inline const ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage& flexible_linkage(int index) const;
  inline ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage* mutable_flexible_linkage(int index);
  inline ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage* add_flexible_linkage();
  inline const ::google::protobuf::RepeatedPtrField< ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage >&
      flexible_linkage() const;
  inline ::google::protobuf::RepeatedPtrField< ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage >*
      mutable_flexible_linkage();
  
  // @@protoc_insertion_point(class_scope:molecular_dynamics.oligosaccharide_builder.BuildResults.Structure)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage > flexible_linkage_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_proto_2fBuildResultsPB_2eproto();
  friend void protobuf_AssignDesc_proto_2fBuildResultsPB_2eproto();
  friend void protobuf_ShutdownFile_proto_2fBuildResultsPB_2eproto();
  
  void InitAsDefaultInstance();
  static BuildResults_Structure* default_instance_;
};
// -------------------------------------------------------------------

class BuildResults : public ::google::protobuf::Message {
 public:
  BuildResults();
  virtual ~BuildResults();
  
  BuildResults(const BuildResults& from);
  
  inline BuildResults& operator=(const BuildResults& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const BuildResults& default_instance();
  
  void Swap(BuildResults* other);
  
  // implements Message ----------------------------------------------
  
  BuildResults* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BuildResults& from);
  void MergeFrom(const BuildResults& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef BuildResults_FlexibleLinkage FlexibleLinkage;
  typedef BuildResults_Structure Structure;
  
  // accessors -------------------------------------------------------
  
  // repeated .molecular_dynamics.oligosaccharide_builder.BuildResults.Structure structure = 1;
  inline int structure_size() const;
  inline void clear_structure();
  static const int kStructureFieldNumber = 1;
  inline const ::molecular_dynamics::oligosaccharide_builder::BuildResults_Structure& structure(int index) const;
  inline ::molecular_dynamics::oligosaccharide_builder::BuildResults_Structure* mutable_structure(int index);
  inline ::molecular_dynamics::oligosaccharide_builder::BuildResults_Structure* add_structure();
  inline const ::google::protobuf::RepeatedPtrField< ::molecular_dynamics::oligosaccharide_builder::BuildResults_Structure >&
      structure() const;
  inline ::google::protobuf::RepeatedPtrField< ::molecular_dynamics::oligosaccharide_builder::BuildResults_Structure >*
      mutable_structure();
  
  // @@protoc_insertion_point(class_scope:molecular_dynamics.oligosaccharide_builder.BuildResults)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::molecular_dynamics::oligosaccharide_builder::BuildResults_Structure > structure_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_proto_2fBuildResultsPB_2eproto();
  friend void protobuf_AssignDesc_proto_2fBuildResultsPB_2eproto();
  friend void protobuf_ShutdownFile_proto_2fBuildResultsPB_2eproto();
  
  void InitAsDefaultInstance();
  static BuildResults* default_instance_;
};
// ===================================================================


// ===================================================================

// BuildResults_FlexibleLinkage

// required int32 index = 1;
inline bool BuildResults_FlexibleLinkage::has_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BuildResults_FlexibleLinkage::set_has_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BuildResults_FlexibleLinkage::clear_has_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BuildResults_FlexibleLinkage::clear_index() {
  index_ = 0;
  clear_has_index();
}
inline ::google::protobuf::int32 BuildResults_FlexibleLinkage::index() const {
  return index_;
}
inline void BuildResults_FlexibleLinkage::set_index(::google::protobuf::int32 value) {
  set_has_index();
  index_ = value;
}

// required .molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage.Angle angle = 2;
inline bool BuildResults_FlexibleLinkage::has_angle() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BuildResults_FlexibleLinkage::set_has_angle() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BuildResults_FlexibleLinkage::clear_has_angle() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BuildResults_FlexibleLinkage::clear_angle() {
  angle_ = 0;
  clear_has_angle();
}
inline ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage_Angle BuildResults_FlexibleLinkage::angle() const {
  return static_cast< ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage_Angle >(angle_);
}
inline void BuildResults_FlexibleLinkage::set_angle(::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage_Angle value) {
  GOOGLE_DCHECK(::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage_Angle_IsValid(value));
  set_has_angle();
  angle_ = value;
}

// required double value = 3;
inline bool BuildResults_FlexibleLinkage::has_value() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BuildResults_FlexibleLinkage::set_has_value() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BuildResults_FlexibleLinkage::clear_has_value() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BuildResults_FlexibleLinkage::clear_value() {
  value_ = 0;
  clear_has_value();
}
inline double BuildResults_FlexibleLinkage::value() const {
  return value_;
}
inline void BuildResults_FlexibleLinkage::set_value(double value) {
  set_has_value();
  value_ = value;
}

// -------------------------------------------------------------------

// BuildResults_Structure

// repeated .molecular_dynamics.oligosaccharide_builder.BuildResults.FlexibleLinkage flexible_linkage = 1;
inline int BuildResults_Structure::flexible_linkage_size() const {
  return flexible_linkage_.size();
}
inline void BuildResults_Structure::clear_flexible_linkage() {
  flexible_linkage_.Clear();
}
inline const ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage& BuildResults_Structure::flexible_linkage(int index) const {
  return flexible_linkage_.Get(index);
}
inline ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage* BuildResults_Structure::mutable_flexible_linkage(int index) {
  return flexible_linkage_.Mutable(index);
}
inline ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage* BuildResults_Structure::add_flexible_linkage() {
  return flexible_linkage_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage >&
BuildResults_Structure::flexible_linkage() const {
  return flexible_linkage_;
}
inline ::google::protobuf::RepeatedPtrField< ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage >*
BuildResults_Structure::mutable_flexible_linkage() {
  return &flexible_linkage_;
}

// -------------------------------------------------------------------

// BuildResults

// repeated .molecular_dynamics.oligosaccharide_builder.BuildResults.Structure structure = 1;
inline int BuildResults::structure_size() const {
  return structure_.size();
}
inline void BuildResults::clear_structure() {
  structure_.Clear();
}
inline const ::molecular_dynamics::oligosaccharide_builder::BuildResults_Structure& BuildResults::structure(int index) const {
  return structure_.Get(index);
}
inline ::molecular_dynamics::oligosaccharide_builder::BuildResults_Structure* BuildResults::mutable_structure(int index) {
  return structure_.Mutable(index);
}
inline ::molecular_dynamics::oligosaccharide_builder::BuildResults_Structure* BuildResults::add_structure() {
  return structure_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::molecular_dynamics::oligosaccharide_builder::BuildResults_Structure >&
BuildResults::structure() const {
  return structure_;
}
inline ::google::protobuf::RepeatedPtrField< ::molecular_dynamics::oligosaccharide_builder::BuildResults_Structure >*
BuildResults::mutable_structure() {
  return &structure_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace oligosaccharide_builder
}  // namespace molecular_dynamics

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage_Angle>() {
  return ::molecular_dynamics::oligosaccharide_builder::BuildResults_FlexibleLinkage_Angle_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fBuildResultsPB_2eproto__INCLUDED
