// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildInfoPB.proto

package org.glycam.molecular_dynamics.oligosaccharide_builder;

public final class BuildInfoPB {
  private BuildInfoPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BuildInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string glycan = 1;
    boolean hasGlycan();
    java.lang.String getGlycan();
    
    // repeated .molecular_dynamics.oligosaccharide_builder.BuildInfo.Linkage linkage = 2;
    java.util.List<org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage> 
        getLinkageList();
    org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage getLinkage(int index);
    int getLinkageCount();
    java.util.List<? extends org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.LinkageOrBuilder> 
        getLinkageOrBuilderList();
    org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.LinkageOrBuilder getLinkageOrBuilder(
        int index);
    
    // optional .molecular_dynamics.oligosaccharide_builder.SolvationInfo solvation_info = 3;
    boolean hasSolvationInfo();
    org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo getSolvationInfo();
    org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfoOrBuilder getSolvationInfoOrBuilder();
  }
  public static final class BuildInfo extends
      com.google.protobuf.GeneratedMessage
      implements BuildInfoOrBuilder {
    // Use BuildInfo.newBuilder() to construct.
    private BuildInfo(Builder builder) {
      super(builder);
    }
    private BuildInfo(boolean noInit) {}
    
    private static final BuildInfo defaultInstance;
    public static BuildInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public BuildInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_fieldAccessorTable;
    }
    
    public interface LinkageOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // repeated double phi_value = 1;
      java.util.List<java.lang.Double> getPhiValueList();
      int getPhiValueCount();
      double getPhiValue(int index);
      
      // repeated double psi_value = 2;
      java.util.List<java.lang.Double> getPsiValueList();
      int getPsiValueCount();
      double getPsiValue(int index);
      
      // repeated double omega_value = 3;
      java.util.List<java.lang.Double> getOmegaValueList();
      int getOmegaValueCount();
      double getOmegaValue(int index);
    }
    public static final class Linkage extends
        com.google.protobuf.GeneratedMessage
        implements LinkageOrBuilder {
      // Use Linkage.newBuilder() to construct.
      private Linkage(Builder builder) {
        super(builder);
      }
      private Linkage(boolean noInit) {}
      
      private static final Linkage defaultInstance;
      public static Linkage getDefaultInstance() {
        return defaultInstance;
      }
      
      public Linkage getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_Linkage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_Linkage_fieldAccessorTable;
      }
      
      // repeated double phi_value = 1;
      public static final int PHI_VALUE_FIELD_NUMBER = 1;
      private java.util.List<java.lang.Double> phiValue_;
      public java.util.List<java.lang.Double>
          getPhiValueList() {
        return phiValue_;
      }
      public int getPhiValueCount() {
        return phiValue_.size();
      }
      public double getPhiValue(int index) {
        return phiValue_.get(index);
      }
      
      // repeated double psi_value = 2;
      public static final int PSI_VALUE_FIELD_NUMBER = 2;
      private java.util.List<java.lang.Double> psiValue_;
      public java.util.List<java.lang.Double>
          getPsiValueList() {
        return psiValue_;
      }
      public int getPsiValueCount() {
        return psiValue_.size();
      }
      public double getPsiValue(int index) {
        return psiValue_.get(index);
      }
      
      // repeated double omega_value = 3;
      public static final int OMEGA_VALUE_FIELD_NUMBER = 3;
      private java.util.List<java.lang.Double> omegaValue_;
      public java.util.List<java.lang.Double>
          getOmegaValueList() {
        return omegaValue_;
      }
      public int getOmegaValueCount() {
        return omegaValue_.size();
      }
      public double getOmegaValue(int index) {
        return omegaValue_.get(index);
      }
      
      private void initFields() {
        phiValue_ = java.util.Collections.emptyList();
        psiValue_ = java.util.Collections.emptyList();
        omegaValue_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < phiValue_.size(); i++) {
          output.writeDouble(1, phiValue_.get(i));
        }
        for (int i = 0; i < psiValue_.size(); i++) {
          output.writeDouble(2, psiValue_.get(i));
        }
        for (int i = 0; i < omegaValue_.size(); i++) {
          output.writeDouble(3, omegaValue_.get(i));
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        {
          int dataSize = 0;
          dataSize = 8 * getPhiValueList().size();
          size += dataSize;
          size += 1 * getPhiValueList().size();
        }
        {
          int dataSize = 0;
          dataSize = 8 * getPsiValueList().size();
          size += dataSize;
          size += 1 * getPsiValueList().size();
        }
        {
          int dataSize = 0;
          dataSize = 8 * getOmegaValueList().size();
          size += dataSize;
          size += 1 * getOmegaValueList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.LinkageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_Linkage_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_Linkage_fieldAccessorTable;
        }
        
        // Construct using org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          phiValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          psiValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          omegaValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.getDescriptor();
        }
        
        public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage getDefaultInstanceForType() {
          return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.getDefaultInstance();
        }
        
        public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage build() {
          org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage buildPartial() {
          org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage result = new org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            phiValue_ = java.util.Collections.unmodifiableList(phiValue_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.phiValue_ = phiValue_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            psiValue_ = java.util.Collections.unmodifiableList(psiValue_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.psiValue_ = psiValue_;
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            omegaValue_ = java.util.Collections.unmodifiableList(omegaValue_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.omegaValue_ = omegaValue_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage) {
            return mergeFrom((org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage other) {
          if (other == org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.getDefaultInstance()) return this;
          if (!other.phiValue_.isEmpty()) {
            if (phiValue_.isEmpty()) {
              phiValue_ = other.phiValue_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePhiValueIsMutable();
              phiValue_.addAll(other.phiValue_);
            }
            onChanged();
          }
          if (!other.psiValue_.isEmpty()) {
            if (psiValue_.isEmpty()) {
              psiValue_ = other.psiValue_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePsiValueIsMutable();
              psiValue_.addAll(other.psiValue_);
            }
            onChanged();
          }
          if (!other.omegaValue_.isEmpty()) {
            if (omegaValue_.isEmpty()) {
              omegaValue_ = other.omegaValue_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureOmegaValueIsMutable();
              omegaValue_.addAll(other.omegaValue_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 9: {
                ensurePhiValueIsMutable();
                phiValue_.add(input.readDouble());
                break;
              }
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                while (input.getBytesUntilLimit() > 0) {
                  addPhiValue(input.readDouble());
                }
                input.popLimit(limit);
                break;
              }
              case 17: {
                ensurePsiValueIsMutable();
                psiValue_.add(input.readDouble());
                break;
              }
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                while (input.getBytesUntilLimit() > 0) {
                  addPsiValue(input.readDouble());
                }
                input.popLimit(limit);
                break;
              }
              case 25: {
                ensureOmegaValueIsMutable();
                omegaValue_.add(input.readDouble());
                break;
              }
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                while (input.getBytesUntilLimit() > 0) {
                  addOmegaValue(input.readDouble());
                }
                input.popLimit(limit);
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // repeated double phi_value = 1;
        private java.util.List<java.lang.Double> phiValue_ = java.util.Collections.emptyList();
        private void ensurePhiValueIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            phiValue_ = new java.util.ArrayList<java.lang.Double>(phiValue_);
            bitField0_ |= 0x00000001;
           }
        }
        public java.util.List<java.lang.Double>
            getPhiValueList() {
          return java.util.Collections.unmodifiableList(phiValue_);
        }
        public int getPhiValueCount() {
          return phiValue_.size();
        }
        public double getPhiValue(int index) {
          return phiValue_.get(index);
        }
        public Builder setPhiValue(
            int index, double value) {
          ensurePhiValueIsMutable();
          phiValue_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addPhiValue(double value) {
          ensurePhiValueIsMutable();
          phiValue_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllPhiValue(
            java.lang.Iterable<? extends java.lang.Double> values) {
          ensurePhiValueIsMutable();
          super.addAll(values, phiValue_);
          onChanged();
          return this;
        }
        public Builder clearPhiValue() {
          phiValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        
        // repeated double psi_value = 2;
        private java.util.List<java.lang.Double> psiValue_ = java.util.Collections.emptyList();
        private void ensurePsiValueIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            psiValue_ = new java.util.ArrayList<java.lang.Double>(psiValue_);
            bitField0_ |= 0x00000002;
           }
        }
        public java.util.List<java.lang.Double>
            getPsiValueList() {
          return java.util.Collections.unmodifiableList(psiValue_);
        }
        public int getPsiValueCount() {
          return psiValue_.size();
        }
        public double getPsiValue(int index) {
          return psiValue_.get(index);
        }
        public Builder setPsiValue(
            int index, double value) {
          ensurePsiValueIsMutable();
          psiValue_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addPsiValue(double value) {
          ensurePsiValueIsMutable();
          psiValue_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllPsiValue(
            java.lang.Iterable<? extends java.lang.Double> values) {
          ensurePsiValueIsMutable();
          super.addAll(values, psiValue_);
          onChanged();
          return this;
        }
        public Builder clearPsiValue() {
          psiValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        
        // repeated double omega_value = 3;
        private java.util.List<java.lang.Double> omegaValue_ = java.util.Collections.emptyList();
        private void ensureOmegaValueIsMutable() {
          if (!((bitField0_ & 0x00000004) == 0x00000004)) {
            omegaValue_ = new java.util.ArrayList<java.lang.Double>(omegaValue_);
            bitField0_ |= 0x00000004;
           }
        }
        public java.util.List<java.lang.Double>
            getOmegaValueList() {
          return java.util.Collections.unmodifiableList(omegaValue_);
        }
        public int getOmegaValueCount() {
          return omegaValue_.size();
        }
        public double getOmegaValue(int index) {
          return omegaValue_.get(index);
        }
        public Builder setOmegaValue(
            int index, double value) {
          ensureOmegaValueIsMutable();
          omegaValue_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addOmegaValue(double value) {
          ensureOmegaValueIsMutable();
          omegaValue_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllOmegaValue(
            java.lang.Iterable<? extends java.lang.Double> values) {
          ensureOmegaValueIsMutable();
          super.addAll(values, omegaValue_);
          onChanged();
          return this;
        }
        public Builder clearOmegaValue() {
          omegaValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:molecular_dynamics.oligosaccharide_builder.BuildInfo.Linkage)
      }
      
      static {
        defaultInstance = new Linkage(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:molecular_dynamics.oligosaccharide_builder.BuildInfo.Linkage)
    }
    
    private int bitField0_;
    // required string glycan = 1;
    public static final int GLYCAN_FIELD_NUMBER = 1;
    private java.lang.Object glycan_;
    public boolean hasGlycan() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public java.lang.String getGlycan() {
      java.lang.Object ref = glycan_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          glycan_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGlycanBytes() {
      java.lang.Object ref = glycan_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        glycan_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .molecular_dynamics.oligosaccharide_builder.BuildInfo.Linkage linkage = 2;
    public static final int LINKAGE_FIELD_NUMBER = 2;
    private java.util.List<org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage> linkage_;
    public java.util.List<org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage> getLinkageList() {
      return linkage_;
    }
    public java.util.List<? extends org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.LinkageOrBuilder> 
        getLinkageOrBuilderList() {
      return linkage_;
    }
    public int getLinkageCount() {
      return linkage_.size();
    }
    public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage getLinkage(int index) {
      return linkage_.get(index);
    }
    public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.LinkageOrBuilder getLinkageOrBuilder(
        int index) {
      return linkage_.get(index);
    }
    
    // optional .molecular_dynamics.oligosaccharide_builder.SolvationInfo solvation_info = 3;
    public static final int SOLVATION_INFO_FIELD_NUMBER = 3;
    private org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo solvationInfo_;
    public boolean hasSolvationInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo getSolvationInfo() {
      return solvationInfo_;
    }
    public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfoOrBuilder getSolvationInfoOrBuilder() {
      return solvationInfo_;
    }
    
    private void initFields() {
      glycan_ = "";
      linkage_ = java.util.Collections.emptyList();
      solvationInfo_ = org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasGlycan()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasSolvationInfo()) {
        if (!getSolvationInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGlycanBytes());
      }
      for (int i = 0; i < linkage_.size(); i++) {
        output.writeMessage(2, linkage_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, solvationInfo_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGlycanBytes());
      }
      for (int i = 0; i < linkage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, linkage_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, solvationInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_fieldAccessorTable;
      }
      
      // Construct using org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLinkageFieldBuilder();
          getSolvationInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        glycan_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (linkageBuilder_ == null) {
          linkage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          linkageBuilder_.clear();
        }
        if (solvationInfoBuilder_ == null) {
          solvationInfo_ = org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.getDefaultInstance();
        } else {
          solvationInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.getDescriptor();
      }
      
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo getDefaultInstanceForType() {
        return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.getDefaultInstance();
      }
      
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo build() {
        org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo buildPartial() {
        org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo result = new org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.glycan_ = glycan_;
        if (linkageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            linkage_ = java.util.Collections.unmodifiableList(linkage_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.linkage_ = linkage_;
        } else {
          result.linkage_ = linkageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (solvationInfoBuilder_ == null) {
          result.solvationInfo_ = solvationInfo_;
        } else {
          result.solvationInfo_ = solvationInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo) {
          return mergeFrom((org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo other) {
        if (other == org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.getDefaultInstance()) return this;
        if (other.hasGlycan()) {
          setGlycan(other.getGlycan());
        }
        if (linkageBuilder_ == null) {
          if (!other.linkage_.isEmpty()) {
            if (linkage_.isEmpty()) {
              linkage_ = other.linkage_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureLinkageIsMutable();
              linkage_.addAll(other.linkage_);
            }
            onChanged();
          }
        } else {
          if (!other.linkage_.isEmpty()) {
            if (linkageBuilder_.isEmpty()) {
              linkageBuilder_.dispose();
              linkageBuilder_ = null;
              linkage_ = other.linkage_;
              bitField0_ = (bitField0_ & ~0x00000002);
              linkageBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLinkageFieldBuilder() : null;
            } else {
              linkageBuilder_.addAllMessages(other.linkage_);
            }
          }
        }
        if (other.hasSolvationInfo()) {
          mergeSolvationInfo(other.getSolvationInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasGlycan()) {
          
          return false;
        }
        if (hasSolvationInfo()) {
          if (!getSolvationInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              glycan_ = input.readBytes();
              break;
            }
            case 18: {
              org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.Builder subBuilder = org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addLinkage(subBuilder.buildPartial());
              break;
            }
            case 26: {
              org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Builder subBuilder = org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.newBuilder();
              if (hasSolvationInfo()) {
                subBuilder.mergeFrom(getSolvationInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSolvationInfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string glycan = 1;
      private java.lang.Object glycan_ = "";
      public boolean hasGlycan() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public java.lang.String getGlycan() {
        java.lang.Object ref = glycan_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          glycan_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      public Builder setGlycan(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        glycan_ = value;
        onChanged();
        return this;
      }
      public Builder clearGlycan() {
        bitField0_ = (bitField0_ & ~0x00000001);
        glycan_ = getDefaultInstance().getGlycan();
        onChanged();
        return this;
      }
      void setGlycan(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        glycan_ = value;
        onChanged();
      }
      
      // repeated .molecular_dynamics.oligosaccharide_builder.BuildInfo.Linkage linkage = 2;
      private java.util.List<org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage> linkage_ =
        java.util.Collections.emptyList();
      private void ensureLinkageIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          linkage_ = new java.util.ArrayList<org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage>(linkage_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.Builder, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.LinkageOrBuilder> linkageBuilder_;
      
      public java.util.List<org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage> getLinkageList() {
        if (linkageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(linkage_);
        } else {
          return linkageBuilder_.getMessageList();
        }
      }
      public int getLinkageCount() {
        if (linkageBuilder_ == null) {
          return linkage_.size();
        } else {
          return linkageBuilder_.getCount();
        }
      }
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage getLinkage(int index) {
        if (linkageBuilder_ == null) {
          return linkage_.get(index);
        } else {
          return linkageBuilder_.getMessage(index);
        }
      }
      public Builder setLinkage(
          int index, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage value) {
        if (linkageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkageIsMutable();
          linkage_.set(index, value);
          onChanged();
        } else {
          linkageBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setLinkage(
          int index, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.Builder builderForValue) {
        if (linkageBuilder_ == null) {
          ensureLinkageIsMutable();
          linkage_.set(index, builderForValue.build());
          onChanged();
        } else {
          linkageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addLinkage(org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage value) {
        if (linkageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkageIsMutable();
          linkage_.add(value);
          onChanged();
        } else {
          linkageBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addLinkage(
          int index, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage value) {
        if (linkageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkageIsMutable();
          linkage_.add(index, value);
          onChanged();
        } else {
          linkageBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addLinkage(
          org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.Builder builderForValue) {
        if (linkageBuilder_ == null) {
          ensureLinkageIsMutable();
          linkage_.add(builderForValue.build());
          onChanged();
        } else {
          linkageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addLinkage(
          int index, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.Builder builderForValue) {
        if (linkageBuilder_ == null) {
          ensureLinkageIsMutable();
          linkage_.add(index, builderForValue.build());
          onChanged();
        } else {
          linkageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllLinkage(
          java.lang.Iterable<? extends org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage> values) {
        if (linkageBuilder_ == null) {
          ensureLinkageIsMutable();
          super.addAll(values, linkage_);
          onChanged();
        } else {
          linkageBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearLinkage() {
        if (linkageBuilder_ == null) {
          linkage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          linkageBuilder_.clear();
        }
        return this;
      }
      public Builder removeLinkage(int index) {
        if (linkageBuilder_ == null) {
          ensureLinkageIsMutable();
          linkage_.remove(index);
          onChanged();
        } else {
          linkageBuilder_.remove(index);
        }
        return this;
      }
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.Builder getLinkageBuilder(
          int index) {
        return getLinkageFieldBuilder().getBuilder(index);
      }
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.LinkageOrBuilder getLinkageOrBuilder(
          int index) {
        if (linkageBuilder_ == null) {
          return linkage_.get(index);  } else {
          return linkageBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.LinkageOrBuilder> 
           getLinkageOrBuilderList() {
        if (linkageBuilder_ != null) {
          return linkageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(linkage_);
        }
      }
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.Builder addLinkageBuilder() {
        return getLinkageFieldBuilder().addBuilder(
            org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.getDefaultInstance());
      }
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.Builder addLinkageBuilder(
          int index) {
        return getLinkageFieldBuilder().addBuilder(
            index, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.getDefaultInstance());
      }
      public java.util.List<org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.Builder> 
           getLinkageBuilderList() {
        return getLinkageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.Builder, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.LinkageOrBuilder> 
          getLinkageFieldBuilder() {
        if (linkageBuilder_ == null) {
          linkageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.Builder, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.LinkageOrBuilder>(
                  linkage_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          linkage_ = null;
        }
        return linkageBuilder_;
      }
      
      // optional .molecular_dynamics.oligosaccharide_builder.SolvationInfo solvation_info = 3;
      private org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo solvationInfo_ = org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Builder, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfoOrBuilder> solvationInfoBuilder_;
      public boolean hasSolvationInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo getSolvationInfo() {
        if (solvationInfoBuilder_ == null) {
          return solvationInfo_;
        } else {
          return solvationInfoBuilder_.getMessage();
        }
      }
      public Builder setSolvationInfo(org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo value) {
        if (solvationInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          solvationInfo_ = value;
          onChanged();
        } else {
          solvationInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setSolvationInfo(
          org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Builder builderForValue) {
        if (solvationInfoBuilder_ == null) {
          solvationInfo_ = builderForValue.build();
          onChanged();
        } else {
          solvationInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeSolvationInfo(org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo value) {
        if (solvationInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              solvationInfo_ != org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.getDefaultInstance()) {
            solvationInfo_ =
              org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.newBuilder(solvationInfo_).mergeFrom(value).buildPartial();
          } else {
            solvationInfo_ = value;
          }
          onChanged();
        } else {
          solvationInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearSolvationInfo() {
        if (solvationInfoBuilder_ == null) {
          solvationInfo_ = org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.getDefaultInstance();
          onChanged();
        } else {
          solvationInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Builder getSolvationInfoBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSolvationInfoFieldBuilder().getBuilder();
      }
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfoOrBuilder getSolvationInfoOrBuilder() {
        if (solvationInfoBuilder_ != null) {
          return solvationInfoBuilder_.getMessageOrBuilder();
        } else {
          return solvationInfo_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Builder, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfoOrBuilder> 
          getSolvationInfoFieldBuilder() {
        if (solvationInfoBuilder_ == null) {
          solvationInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Builder, org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfoOrBuilder>(
                  solvationInfo_,
                  getParentForChildren(),
                  isClean());
          solvationInfo_ = null;
        }
        return solvationInfoBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:molecular_dynamics.oligosaccharide_builder.BuildInfo)
    }
    
    static {
      defaultInstance = new BuildInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:molecular_dynamics.oligosaccharide_builder.BuildInfo)
  }
  
  public interface SolvationInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .molecular_dynamics.oligosaccharide_builder.SolvationInfo.Shape shape = 1 [default = CUBIC];
    boolean hasShape();
    org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Shape getShape();
    
    // required double distance = 2;
    boolean hasDistance();
    double getDistance();
    
    // required double closeness = 3;
    boolean hasCloseness();
    double getCloseness();
  }
  public static final class SolvationInfo extends
      com.google.protobuf.GeneratedMessage
      implements SolvationInfoOrBuilder {
    // Use SolvationInfo.newBuilder() to construct.
    private SolvationInfo(Builder builder) {
      super(builder);
    }
    private SolvationInfo(boolean noInit) {}
    
    private static final SolvationInfo defaultInstance;
    public static SolvationInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public SolvationInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.internal_static_molecular_dynamics_oligosaccharide_builder_SolvationInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.internal_static_molecular_dynamics_oligosaccharide_builder_SolvationInfo_fieldAccessorTable;
    }
    
    public enum Shape
        implements com.google.protobuf.ProtocolMessageEnum {
      CUBIC(0, 0),
      RECTANGULAR(1, 1),
      ;
      
      public static final int CUBIC_VALUE = 0;
      public static final int RECTANGULAR_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Shape valueOf(int value) {
        switch (value) {
          case 0: return CUBIC;
          case 1: return RECTANGULAR;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Shape>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Shape>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Shape>() {
              public Shape findValueByNumber(int number) {
                return Shape.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Shape[] VALUES = {
        CUBIC, RECTANGULAR, 
      };
      
      public static Shape valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Shape(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:molecular_dynamics.oligosaccharide_builder.SolvationInfo.Shape)
    }
    
    private int bitField0_;
    // required .molecular_dynamics.oligosaccharide_builder.SolvationInfo.Shape shape = 1 [default = CUBIC];
    public static final int SHAPE_FIELD_NUMBER = 1;
    private org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Shape shape_;
    public boolean hasShape() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Shape getShape() {
      return shape_;
    }
    
    // required double distance = 2;
    public static final int DISTANCE_FIELD_NUMBER = 2;
    private double distance_;
    public boolean hasDistance() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getDistance() {
      return distance_;
    }
    
    // required double closeness = 3;
    public static final int CLOSENESS_FIELD_NUMBER = 3;
    private double closeness_;
    public boolean hasCloseness() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getCloseness() {
      return closeness_;
    }
    
    private void initFields() {
      shape_ = org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Shape.CUBIC;
      distance_ = 0D;
      closeness_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasShape()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDistance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCloseness()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, shape_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, distance_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, closeness_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, shape_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, distance_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, closeness_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.internal_static_molecular_dynamics_oligosaccharide_builder_SolvationInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.internal_static_molecular_dynamics_oligosaccharide_builder_SolvationInfo_fieldAccessorTable;
      }
      
      // Construct using org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        shape_ = org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Shape.CUBIC;
        bitField0_ = (bitField0_ & ~0x00000001);
        distance_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        closeness_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.getDescriptor();
      }
      
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo getDefaultInstanceForType() {
        return org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.getDefaultInstance();
      }
      
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo build() {
        org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo buildPartial() {
        org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo result = new org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.shape_ = shape_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.distance_ = distance_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.closeness_ = closeness_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo) {
          return mergeFrom((org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo other) {
        if (other == org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.getDefaultInstance()) return this;
        if (other.hasShape()) {
          setShape(other.getShape());
        }
        if (other.hasDistance()) {
          setDistance(other.getDistance());
        }
        if (other.hasCloseness()) {
          setCloseness(other.getCloseness());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasShape()) {
          
          return false;
        }
        if (!hasDistance()) {
          
          return false;
        }
        if (!hasCloseness()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Shape value = org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Shape.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                shape_ = value;
              }
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              distance_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              closeness_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .molecular_dynamics.oligosaccharide_builder.SolvationInfo.Shape shape = 1 [default = CUBIC];
      private org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Shape shape_ = org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Shape.CUBIC;
      public boolean hasShape() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Shape getShape() {
        return shape_;
      }
      public Builder setShape(org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Shape value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        shape_ = value;
        onChanged();
        return this;
      }
      public Builder clearShape() {
        bitField0_ = (bitField0_ & ~0x00000001);
        shape_ = org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Shape.CUBIC;
        onChanged();
        return this;
      }
      
      // required double distance = 2;
      private double distance_ ;
      public boolean hasDistance() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getDistance() {
        return distance_;
      }
      public Builder setDistance(double value) {
        bitField0_ |= 0x00000002;
        distance_ = value;
        onChanged();
        return this;
      }
      public Builder clearDistance() {
        bitField0_ = (bitField0_ & ~0x00000002);
        distance_ = 0D;
        onChanged();
        return this;
      }
      
      // required double closeness = 3;
      private double closeness_ ;
      public boolean hasCloseness() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getCloseness() {
        return closeness_;
      }
      public Builder setCloseness(double value) {
        bitField0_ |= 0x00000004;
        closeness_ = value;
        onChanged();
        return this;
      }
      public Builder clearCloseness() {
        bitField0_ = (bitField0_ & ~0x00000004);
        closeness_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:molecular_dynamics.oligosaccharide_builder.SolvationInfo)
    }
    
    static {
      defaultInstance = new SolvationInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:molecular_dynamics.oligosaccharide_builder.SolvationInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_Linkage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_Linkage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_molecular_dynamics_oligosaccharide_builder_SolvationInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_molecular_dynamics_oligosaccharide_builder_SolvationInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BuildInfoPB.proto\022*molecular_dynamics." +
      "oligosaccharide_builder\"\204\002\n\tBuildInfo\022\016\n" +
      "\006glycan\030\001 \002(\t\022N\n\007linkage\030\002 \003(\0132=.molecul" +
      "ar_dynamics.oligosaccharide_builder.Buil" +
      "dInfo.Linkage\022Q\n\016solvation_info\030\003 \001(\01329." +
      "molecular_dynamics.oligosaccharide_build" +
      "er.SolvationInfo\032D\n\007Linkage\022\021\n\tphi_value" +
      "\030\001 \003(\001\022\021\n\tpsi_value\030\002 \003(\001\022\023\n\013omega_value" +
      "\030\003 \003(\001\"\260\001\n\rSolvationInfo\022U\n\005shape\030\001 \002(\0162" +
      "?.molecular_dynamics.oligosaccharide_bui",
      "lder.SolvationInfo.Shape:\005CUBIC\022\020\n\010dista" +
      "nce\030\002 \002(\001\022\021\n\tcloseness\030\003 \002(\001\"#\n\005Shape\022\t\n" +
      "\005CUBIC\020\000\022\017\n\013RECTANGULAR\020\001B7\n5org.glycam." +
      "molecular_dynamics.oligosaccharide_build" +
      "er"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_descriptor,
              new java.lang.String[] { "Glycan", "Linkage", "SolvationInfo", },
              org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.class,
              org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Builder.class);
          internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_Linkage_descriptor =
            internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_descriptor.getNestedTypes().get(0);
          internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_Linkage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_molecular_dynamics_oligosaccharide_builder_BuildInfo_Linkage_descriptor,
              new java.lang.String[] { "PhiValue", "PsiValue", "OmegaValue", },
              org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.class,
              org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.BuildInfo.Linkage.Builder.class);
          internal_static_molecular_dynamics_oligosaccharide_builder_SolvationInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_molecular_dynamics_oligosaccharide_builder_SolvationInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_molecular_dynamics_oligosaccharide_builder_SolvationInfo_descriptor,
              new java.lang.String[] { "Shape", "Distance", "Closeness", },
              org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.class,
              org.glycam.molecular_dynamics.oligosaccharide_builder.BuildInfoPB.SolvationInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
